name: "Example Company"
url:   http://example.com
ga:   "UA-XXXXXXXX-Y"

github_hosted: true

# Posts # # # # # #
show_posts: true
show_bylines: true
limit_posts: 0
# # # # # # # # # #

# Markdown # # # # # # # # # # # # # # # # # # # #
markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]
 # # # # # # # # # # # # # # # # # # # # # # # # #

gems:
    - jekyll-redirect-from
    - jekyll-sitemap

include: [".htaccess"]
exclude:
    - ".travis.yml"
    - "Gemfile"
    - "Gemfile.lock"
    - "README.md"
    - "npm-debug.log"
    - "package.json"
    - ".sass-cache"
    - "node_modules"
    - "s3_website.yml"

sass:
    sass_dir: static/css/
    style: :nested
