name: "Example Company"
url:   http://example.com.tmp2.franklyweb.dk/
ga:   "UA-XXXXXXXX-Y"

markdown: kramdown
kramdown:
    input: GFM
redcarpet:
    extensions: ["smart", "footnotes", "tables"]

limit_posts: 0
